'use client';
import { useEffect, useMemo, useState } from 'react';
import { parseCSV } from '../lib/parser.ts';
import { calculateMetrics, generatePlans, inferCategory, type Plan, type Transaction } from '../lib/domain.ts';

type Profile={monthlyBudget:number;emergencyFundTarget:number;currentNetWorth:number;monthlyDebtPayment:number;dependents:number;incomeStability:'stable'|'variable'|'uncertain';primaryGoal:'emergency'|'debt'|'savings'|'investing'};
type Goal={id:string;name:string;target:number;current:number};
type User={id:string;email:string};
const naira=(n:number)=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(n);

export default function Home(){
 const [user,setUser]=useState<User|null>(null); const [authMode,setAuthMode]=useState<'login'|'signup'>('login'); const [authEmail,setAuthEmail]=useState(''); const [authPassword,setAuthPassword]=useState(''); const [authMessage,setAuthMessage]=useState(''); const [authLoading,setAuthLoading]=useState(true);
 const [tx,setTx]=useState<Transaction[]>([]); const [profile,setProfile]=useState<Profile>({monthlyBudget:600000,emergencyFundTarget:1000000,currentNetWorth:0,monthlyDebtPayment:0,dependents:0,incomeStability:'stable',primaryGoal:'emergency'});
 const [goals,setGoals]=useState<Goal[]>([]); const [selected,setSelected]=useState('balanced'); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(true);
 const m=useMemo(()=>calculateMetrics(tx,profile.monthlyBudget),[tx,profile.monthlyBudget]); const plans=useMemo(()=>generatePlans(m),[m]); const selectedPlan=plans.find(p=>p.id===selected)??plans[0]; const projectedNetWorth=profile.currentNetWorth+(selectedPlan?.monthlySavings??0)*12; const assessmentComplete=profile.monthlyDebtPayment>=0 && profile.primaryGoal && profile.incomeStability && Number.isInteger(profile.dependents);
 useEffect(()=>{fetch('/api/auth/me').then(async r=>r.ok?(setUser((await r.json()).user),true):false).finally(()=>setAuthLoading(false));},[]);
 useEffect(()=>{if(!user)return;Promise.all([fetch('/api/transactions').then(r=>r.ok?r.json():null),fetch('/api/profile').then(r=>r.ok?r.json():null),fetch('/api/goals').then(r=>r.ok?r.json():null)]).then(([t,p,g])=>{if(t?.transactions)setTx(t.transactions);if(p?.profile)setProfile(p.profile);if(g?.goals)setGoals(g.goals)}).catch(()=>setMessage('Could not load your financial data.')).finally(()=>setLoading(false));},[]);
 async function persistTransactions(rows:Transaction[]){const r=await fetch('/api/transactions',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({transactions:rows})});const data=await r.json();if(!r.ok)throw new Error(data.error);setTx(data.transactions);}
 async function importFile(file:File){
  try{
    if(file.name.toLowerCase().endsWith('.pdf')){
      const form=new FormData(); form.set('file',file);
      const r=await fetch('/api/transactions/pdf',{method:'POST',body:form}); const data=await r.json();
      if(!r.ok)throw new Error(data.error); setTx(data.transactions); setMessage(`Imported ${data.count} transactions from the PDF and recalculated your financial picture.`); return;
    }
    const reader=new FileReader(); reader.onload=async()=>{try{const parsed=parseCSV(String(reader.result));await persistTransactions(parsed.map(t=>({...t,category:t.category??inferCategory(t.description,t.amount)})));setMessage(`Imported ${parsed.length} transactions and recalculated your financial picture.`)}catch(e){setMessage(e instanceof Error?e.message:'Could not import statement.')}}; reader.readAsText(file);
  }catch(e){setMessage(e instanceof Error?e.message:'Could not import statement.')}
 }
 async function acceptPlan(plan:Plan){try{const r=await fetch('/api/plans',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({plan})});if(!r.ok)throw new Error();setMessage(`${plan.name} is now your active plan. Track your progress against it from here.`)}catch{setMessage('Could not save the plan.')}}
 async function saveProfile(){try{const r=await fetch('/api/profile',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(profile)});if(!r.ok)throw new Error();setMessage('Financial profile updated.')}catch{setMessage('Could not save your financial profile.')}}
 async function addGoal(){const name=window.prompt('Goal name','Emergency fund');if(!name)return;const target=Number(window.prompt('Target amount','1000000'));if(!Number.isFinite(target)||target<=0)return;const r=await fetch('/api/goals',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,target,current:0})});const data=await r.json();if(r.ok)setGoals(g=>[data.goal,...g]);else setMessage(data.error??'Could not create goal.');}
 if(authLoading)return <main><section className="auth-shell"><div className="auth-card"><span className="eyebrow">PENNYWISE</span><h1>Loading your financial space…</h1></div></section></main>;
 if(!user)return <main><section className="auth-shell"><div className="auth-card"><span className="eyebrow">PENNYWISE</span><h1>{authMode==='login'?'Your money, with a plan.':'Start your financial plan.'}</h1><p>{authMode==='login'?'Sign in to continue to your private financial dashboard.':'Create your private Pennywise workspace.'}</p><form onSubmit={async e=>{e.preventDefault();setAuthMessage('');const endpoint=authMode==='login'?'/api/auth/login':'/api/auth/signup';const r=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:authEmail,password:authPassword})});const d=await r.json();if(r.ok){setUser(d.user);setAuthEmail('');setAuthPassword('');}else setAuthMessage(d.error??'Authentication failed.')}}><label>Email<input type="email" required autoComplete="email" value={authEmail} onChange={e=>setAuthEmail(e.target.value)}/></label><label>Password<input type="password" required minLength={8} autoComplete={authMode==='login'?'current-password':'new-password'} value={authPassword} onChange={e=>setAuthPassword(e.target.value)}/></label><button className="primary" type="submit">{authMode==='login'?'Sign in':'Create account'}</button></form>{authMessage&&<div className="notice">{authMessage}</div>}<button className="text-button" onClick={()=>{setAuthMode(authMode==='login'?'signup':'login');setAuthMessage('')}}>{authMode==='login'?'Create an account':'Already have an account? Sign in'}</button></div></section></main>;
 if(!tx.length)return <main>
  <header><div><span className="eyebrow">PENNYWISE</span><h1>Your money, with a plan.</h1><p>Your private financial workspace is ready. Import a transaction statement to build your first financial picture.</p></div><div className="header-actions"><span className="account">{user.email}</span><button className="secondary" onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});setUser(null);}}>Sign out</button></div></header>
  <section className="empty-state"><span className="eyebrow">FIRST STEP</span><h2>Bring in your transaction history.</h2><p>Start with a CSV or TXT statement. Pennywise will normalise it, categorise transactions deterministically, calculate your financial health and generate your first plans.</p><label className="upload primary-upload">Import statement<input type="file" accept=".csv,.txt,.pdf" onChange={e=>e.target.files?.[0]&&importFile(e.target.files[0])}/></label>{message&&<div className="notice">{message}</div>}</section>
  <section className="panel"><div className="panel-head"><div><span className="eyebrow">FINANCIAL PROFILE</span><h3>Set the guardrails Pennywise plans against</h3></div><button className="secondary" onClick={saveProfile}>Save profile</button></div><div className="form-grid"><label>Current net worth<input type="number" value={profile.currentNetWorth} onChange={e=>setProfile({...profile,currentNetWorth:Number(e.target.value)})}/></label><label>Monthly budget<input type="number" min="0" value={profile.monthlyBudget} onChange={e=>setProfile({...profile,monthlyBudget:Number(e.target.value)})}/></label><label>Monthly debt payment<input type="number" min="0" value={profile.monthlyDebtPayment} onChange={e=>setProfile({...profile,monthlyDebtPayment:Number(e.target.value)})}/></label><label>Dependents<input type="number" min="0" value={profile.dependents} onChange={e=>setProfile({...profile,dependents:Number(e.target.value)})}/></label><label>Income stability<select value={profile.incomeStability} onChange={e=>setProfile({...profile,incomeStability:e.target.value as Profile['incomeStability']})}><option value="stable">Stable</option><option value="variable">Variable</option><option value="uncertain">Uncertain</option></select></label><label>Primary goal<select value={profile.primaryGoal} onChange={e=>setProfile({...profile,primaryGoal:e.target.value as Profile['primaryGoal']})}><option value="emergency">Emergency fund</option><option value="debt">Debt reduction</option><option value="savings">Savings goal</option><option value="investing">Investing</option></select></label></div><div className="notice">{assessmentComplete?'Assessment inputs are ready. Import transactions next to calculate your financial health.':'Complete the assessment inputs above.'}</div></section>
 </main>;
 return <main>
  <header><div><span className="eyebrow">PENNYWISE</span><h1>Your money, with a plan.</h1><p>Understand your behaviour → score it → predict where you are going → act.</p></div><div className="header-actions"><span className="account">{user.email}</span><button className="secondary" onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});setUser(null);}}>Sign out</button><label className="upload">{loading?'Loading…':'Import statement'}<input disabled={loading} type="file" accept=".csv,.txt,.pdf" onChange={e=>e.target.files?.[0]&&importFile(e.target.files[0])}/></label></div></header>
  <section className="hero"><div><span className="eyebrow">FINANCIAL HEALTH</span><h2>{m.spendingScore}<small>/100</small></h2><p>Spending score</p></div><div className="hero-copy"><strong>{m.savingsRate>=.3?'You are building momentum.':'There is room to strengthen your month.'}</strong><span>Based on {tx.length} transactions, your estimated monthly savings are {naira(m.savings)}.</span></div></section>
  <section className="grid stats">{[['Income',naira(m.income)],['Monthly spend',naira(m.expenses)],['Savings',naira(m.savings)],['Daily budget',naira(m.dailyBudget)]].map(([a,b])=><article className="card" key={a}><span>{a}</span><strong>{b}</strong></article>)}</section>
  <div className="layout"><section className="panel"><div className="panel-head"><div><span className="eyebrow">TRANSACTIONS</span><h3>Recent activity</h3></div><span className="pill">{tx.length} imported</span></div><div className="transactions">{tx.slice(0,12).map(t=><div className="tx" key={t.id}><div><strong>{t.description}</strong><span>{t.date} · {t.category}</span></div><b className={t.amount<0?'negative':'positive'}>{t.amount<0?'−':'+'}{naira(Math.abs(t.amount))}</b></div>)}</div>{message&&<div className="notice">{message}</div>}</section>
  <section className="panel"><div className="panel-head"><div><span className="eyebrow">YOUR NEXT MOVE</span><h3>Choose a plan</h3></div></div><div className="plans">{plans.map(p=><button className={`plan ${selected===p.id?'selected':''}`} key={p.id} onClick={()=>setSelected(p.id)}><div><strong>{p.name}</strong><span>Save {naira(p.monthlySavings)}/month</span></div><b>+{naira(p.projectedGain)}</b><small>12-month projected improvement · discretionary cut {naira(p.cut)}</small></button>)}</div><button className="primary" onClick={()=>acceptPlan(selectedPlan)}>Accept {selectedPlan.name}</button></section></div>
  <section className="panel"><div className="panel-head"><div><span className="eyebrow">FINANCIAL ASSESSMENT</span><h3>Set the guardrails Pennywise plans against</h3></div><button className="secondary" onClick={saveProfile}>Save assessment</button></div><div className="form-grid"><label>Current net worth<input type="number" value={profile.currentNetWorth} onChange={e=>setProfile({...profile,currentNetWorth:Number(e.target.value)})}/></label><label>Monthly budget<input type="number" min="0" value={profile.monthlyBudget} onChange={e=>setProfile({...profile,monthlyBudget:Number(e.target.value)})}/></label><label>Emergency fund target<input type="number" min="0" value={profile.emergencyFundTarget} onChange={e=>setProfile({...profile,emergencyFundTarget:Number(e.target.value)})}/></label><label>Monthly debt payment<input type="number" min="0" value={profile.monthlyDebtPayment} onChange={e=>setProfile({...profile,monthlyDebtPayment:Number(e.target.value)})}/></label><label>Dependents<input type="number" min="0" value={profile.dependents} onChange={e=>setProfile({...profile,dependents:Number(e.target.value)})}/></label><label>Income stability<select value={profile.incomeStability} onChange={e=>setProfile({...profile,incomeStability:e.target.value as Profile['incomeStability']})}><option value="stable">Stable</option><option value="variable">Variable</option><option value="uncertain">Uncertain</option></select></label><label>Primary goal<select value={profile.primaryGoal} onChange={e=>setProfile({...profile,primaryGoal:e.target.value as Profile['primaryGoal']})}><option value="emergency">Emergency fund</option><option value="debt">Debt reduction</option><option value="savings">Savings goal</option><option value="investing">Investing</option></select></label></div></section>
  <section className="panel"><div className="panel-head"><div><span className="eyebrow">12-MONTH PROJECTION</span><h3>Where your current plan points</h3></div><span className="pill">Deterministic projection</span></div><div className="grid stats"><article className="card"><span>Current net worth</span><strong>{naira(profile.currentNetWorth)}</strong></article><article className="card"><span>Projected net worth</span><strong>{naira(projectedNetWorth)}</strong></article><article className="card"><span>12-month savings</span><strong>{naira((selectedPlan?.monthlySavings??0)*12)}</strong></article><article className="card"><span>Projected score</span><strong>{Math.min(100,m.spendingScore+8)}<small>/100</small></strong></article></div></section>
  <section className="panel"><div className="panel-head"><div><span className="eyebrow">SAVINGS GOALS</span><h3>Turn plans into outcomes</h3></div><button className="secondary" onClick={addGoal}>Add goal</button></div>{goals.length?<div className="goals">{goals.map(g=><div className="goal" key={g.id}><div><strong>{g.name}</strong><span>{naira(g.current)} of {naira(g.target)}</span></div><div className="bar"><i style={{width:`${Math.min(100,g.current/g.target*100)}%`}}/></div></div>)}</div>:<p>Create your first savings goal and Pennywise will track it alongside your plan.</p>}</section>
  <section className="panel"><div className="panel-head"><div><span className="eyebrow">ROADMAP</span><h3>What is already real</h3></div></div><div className="roadmap"><span>✓ CSV ingestion + validation</span><span>✓ Deterministic categorisation</span><span>✓ Financial metrics</span><span>✓ Plan generation</span><span>✓ Persistent profile + goals</span><span>✓ Persisted plan acceptance</span><span>○ PDF extraction</span><span>○ Auth + bank integrations</span></div></section>
 </main>;
}
