import assert from 'node:assert/strict';
import { existsSync, readFileSync, rmSync } from 'node:fs';
import { parseCSV } from '../lib/parser.ts';
import { calculateMetrics, generatePlans, inferCategory, normalizeTransactions } from '../lib/domain.ts';
import { validateGoal, validateProfile, validateTransactions } from '../lib/validation.ts';
import { extractPdfTransactions } from '../lib/pdf.ts';
import { registerUser, verifyUser } from '../lib/credentials.ts';

const csv=`date,description,amount,category\n2026-10-01,Salary - Acme,850000,Income\n2026-10-02,Shoprite Ikeja,-24600,Food\n2026-10-03,Bolt,-8400,Transport`;
const rows=parseCSV(csv);
assert.equal(parseCSV('date,description,amount\n2026-10-04,"Shoprite, Ikeja",-24600').length,1);
assert.equal(rows.length,3);
assert.equal(inferCategory('Bolt ride',-8000),'Transport');
const m=calculateMetrics(normalizeTransactions(rows));
assert.equal(m.income,850000); assert.equal(m.expenses,33000); assert.equal(m.savings,817000); assert.equal(generatePlans(m).length,3);
assert.throws(() => parseCSV('date,description,amount\n2026-10-01,Bad,nope'));
assert.throws(() => validateTransactions([{id:'x',date:'bad',description:'x',amount:1}]));
assert.throws(() => validateGoal({name:'',target:1}));
assert.equal(validateProfile({monthlyBudget:500000,emergencyFundTarget:1000000,currentNetWorth:2500000,monthlyDebtPayment:50000,dependents:2,incomeStability:'stable',primaryGoal:'emergency'}).dependents,2);
const pdfRows=await extractPdfTransactions(readFileSync(new URL('../fixtures/statement.pdf', import.meta.url))); assert.equal(pdfRows.length,3); assert.equal(pdfRows[1].amount,-24600); assert.equal(pdfRows[1].category,'Food');

const dbPath=process.env.PENNYWISE_DB_PATH ?? '/tmp/pennywise-verification.sqlite'; rmSync(dbPath,{force:true});
const {createUser,replaceTransactions,listTransactions,saveProfile,getProfile,createGoal,listGoals,savePlan,listPlans}=await import('../lib/db.ts');
const a=createUser({email:'a@example.com',passwordHash:'hash-a',passwordSalt:'salt-a'});
const b=createUser({email:'b@example.com',passwordHash:'hash-b',passwordSalt:'salt-b'});
replaceTransactions(a.id,normalizeTransactions(rows));
assert.equal(listTransactions(a.id).length,3); assert.equal(listTransactions(b.id).length,0); replaceTransactions(b.id,normalizeTransactions(rows)); assert.equal(listTransactions(b.id).length,3);
const beforeAtomic = listTransactions(a.id); assert.throws(() => replaceTransactions(a.id,[beforeAtomic[0], beforeAtomic[0]])); assert.deepEqual(listTransactions(a.id), beforeAtomic);
saveProfile(a.id,{monthlyBudget:500000,emergencyFundTarget:1000000,currentNetWorth:2500000,monthlyDebtPayment:50000,dependents:2,incomeStability:'stable',primaryGoal:'emergency'}); assert.equal(getProfile(a.id).monthlyBudget,500000); assert.equal(getProfile(b.id).monthlyBudget,600000);
createGoal(a.id,{name:'Emergency fund',target:1000000,current:250000}); assert.equal(listGoals(a.id).length,1); assert.equal(listGoals(b.id).length,0);
const plan=generatePlans(m)[0]; savePlan(a.id,plan); assert.equal((listPlans(a.id) as any[])[0].status,'accepted'); assert.equal(listPlans(b.id).length,0);
const authUser=registerUser('auth@example.com','correct-horse-battery-staple'); assert.equal(verifyUser(authUser.email,'correct-horse-battery-staple').id,authUser.id); assert.throws(()=>verifyUser(authUser.email,'wrong-password'));
assert.ok(existsSync(dbPath)); rmSync(dbPath,{force:true});
console.log('Pennywise domain + persistence + user-isolation verification: PASS');
